#!/bin/bash

set -ex

#==================================================
jupyter nbextension enable --py widgetsnbextension --sys-prefix

#==================================================
git clone https://github.com/PBrockmann/fast

#==================================================
pyferretActivate=/srv/conda/envs/notebook/etc/conda/activate.d/pyferret-activate.sh

#==================================================
# Modify env variables to get all fast materials (scripts, palettes)
echo '' >> $pyferretActivate
echo '=========================================' >> $pyferretActivate
echo 'export FER_DATA=". $FER_DATA $HOME/fast"' >> $pyferretActivate
echo 'export FER_GO=". $FER_GO $HOME/fast"' >> $pyferretActivate
echo 'export FER_PALETTE=". /$FER_PALETTE $HOME/fast"' >> $pyferretActivate
echo 'export PATH="$FER_DIR/bin:$HOME/fast:$PATH"' >> $pyferretActivate

#==================================================
# Add directories specific to this repository
echo '' >> $pyferretActivate
echo '=========================================' >> $pyferretActivate
echo 'export FER_GO=". $FER_GO $HOME/files/GO"' >> $pyferretActivate
echo 'export FER_PALETTE=". /$FER_PALETTE $HOME/files/Palettes"' >> $pyferretActivate
